//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace global.cloudis.RealexHPP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HPPMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HPPMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("global.cloudis.RealexHPP.HPPMessages", typeof(HPPMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account must only contain alphanumeric characters.
        /// </summary>
        public static string hppRequest_account_pattern {
            get {
                return ResourceManager.GetString("hppRequest_account_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account must be 30 characters or less.
        /// </summary>
        public static string hppRequest_account_size {
            get {
                return ResourceManager.GetString("hppRequest_account_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be 0 for OTB transactions (where validate card only set to 1).
        /// </summary>
        public static string hppRequest_amount_otb {
            get {
                return ResourceManager.GetString("hppRequest_amount_otb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must only include numeric characters.
        /// </summary>
        public static string hppRequest_amount_pattern {
            get {
                return ResourceManager.GetString("hppRequest_amount_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required and must be 11 characters or less.
        /// </summary>
        public static string hppRequest_amount_size {
            get {
                return ResourceManager.GetString("hppRequest_amount_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto settle flag must be 0, 1, on, off or multi.
        /// </summary>
        public static string hppRequest_autoSettleFlag_pattern {
            get {
                return ResourceManager.GetString("hppRequest_autoSettleFlag_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing code must be of format [digits from postcode]|[digits from address] and contain only a-z A-Z 0-9 , . - / | spaces.
        /// </summary>
        public static string hppRequest_billingCode_pattern {
            get {
                return ResourceManager.GetString("hppRequest_billingCode_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing code must not be more than 60 characters in length.
        /// </summary>
        public static string hppRequest_billingCode_size {
            get {
                return ResourceManager.GetString("hppRequest_billingCode_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing country must only contain the characters A-Z a-z 0-9 , . -.
        /// </summary>
        public static string hppRequest_billingCountry_pattern {
            get {
                return ResourceManager.GetString("hppRequest_billingCountry_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing country must not contain more than 50 characters.
        /// </summary>
        public static string hppRequest_billingCountry_size {
            get {
                return ResourceManager.GetString("hppRequest_billingCountry_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card payment button text must only contain the characters a-z A-Z 0-9 &apos; , + \u201C\u201D ._ - &amp; \ / @!? % ( ) * :£ $ &amp; \u20AC # [] | =.
        /// </summary>
        public static string hppRequest_cardPaymentButtonText_pattern {
            get {
                return ResourceManager.GetString("hppRequest_cardPaymentButtonText_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card payment button text must not contain more than 25 characters.
        /// </summary>
        public static string hppRequest_cardPaymentButtonText_size {
            get {
                return ResourceManager.GetString("hppRequest_cardPaymentButtonText_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card storage enable flag must be 1 or 0.
        /// </summary>
        public static string hppRequest_cardStorageEnable_pattern {
            get {
                return ResourceManager.GetString("hppRequest_cardStorageEnable_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card storage enable flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_cardStorageEnable_size {
            get {
                return ResourceManager.GetString("hppRequest_cardStorageEnable_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel is optional but if set must be either &quot;ECOM&quot; or &quot;MOTO&quot;.
        /// </summary>
        public static string hppRequest_channel_pattern {
            get {
                return ResourceManager.GetString("hppRequest_channel_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel is optional but if set must be either &quot;ECOM&quot; or &quot;MOTO&quot;.
        /// </summary>
        public static string hppRequest_channel_size {
            get {
                return ResourceManager.GetString("hppRequest_channel_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment 1 must only contain the characters a-z A-Z 0-9 &apos; &quot;, + \u201C\u201D ._ - &amp; \ / @ ! ? % ( ) * : £ $ &amp; \u20AC # [ ] | = ; ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷ø¤ùúûüýþÿ\u0152\u017D\u0161\u0153\u017E\u0178¥.
        /// </summary>
        public static string hppRequest_comment1_pattern {
            get {
                return ResourceManager.GetString("hppRequest_comment1_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment 1 must be less than 255 characters in length.
        /// </summary>
        public static string hppRequest_comment1_size {
            get {
                return ResourceManager.GetString("hppRequest_comment1_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment 2 must only contain the characters a-z A-Z 0-9 &apos; &quot;, + \u201C\u201D ._ - &amp; \ / @ ! ? % ( ) * : £ $ &amp; \u20AC # [ ] | = ; ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷ø¤ùúûüýþÿ\u0152\u017D\u0161\u0153\u017E\u0178¥.
        /// </summary>
        public static string hppRequest_comment2_pattern {
            get {
                return ResourceManager.GetString("hppRequest_comment2_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment 2 must be less than 255 characters in length.
        /// </summary>
        public static string hppRequest_comment2_size {
            get {
                return ResourceManager.GetString("hppRequest_comment2_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must only consist of alphabetic characters.
        /// </summary>
        public static string hppRequest_currency_pattern {
            get {
                return ResourceManager.GetString("hppRequest_currency_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required and must be 3 characters in length.
        /// </summary>
        public static string hppRequest_currency_size {
            get {
                return ResourceManager.GetString("hppRequest_currency_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number must only contain the characters a-z A-Z 0-9 - _ . , + @ spaces.
        /// </summary>
        public static string hppRequest_customerNumber_pattern {
            get {
                return ResourceManager.GetString("hppRequest_customerNumber_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number must not contain more than 50 characters.
        /// </summary>
        public static string hppRequest_customerNumber_size {
            get {
                return ResourceManager.GetString("hppRequest_customerNumber_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC enable flag must be 1 or 0.
        /// </summary>
        public static string hppRequest_dccEnable_pattern {
            get {
                return ResourceManager.GetString("hppRequest_dccEnable_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC enable flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_dccEnable_size {
            get {
                return ResourceManager.GetString("hppRequest_dccEnable_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security hash must only contain numeric and a-f characters.
        /// </summary>
        public static string hppRequest_hash_pattern {
            get {
                return ResourceManager.GetString("hppRequest_hash_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security hash must be 40 characters in length.
        /// </summary>
        public static string hppRequest_hash_size {
            get {
                return ResourceManager.GetString("hppRequest_hash_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPP Fraud Filter Mode flag must be ACTIVE, PASSIVE or OFF.
        /// </summary>
        public static string hppRequest_hppFraudFilterMode_pattern {
            get {
                return ResourceManager.GetString("hppRequest_hppFraudFilterMode_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPP Fraud Filter Mode flag must not be more than 7 characters in length.
        /// </summary>
        public static string hppRequest_hppFraudFilterMode_size {
            get {
                return ResourceManager.GetString("hppRequest_hppFraudFilterMode_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select stored card must only contain the characters a-z A-Z\ 0-9 _ spaces.
        /// </summary>
        public static string hppRequest_hppSelectStoredCard_pattern {
            get {
                return ResourceManager.GetString("hppRequest_hppSelectStoredCard_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select stored card must not be more than 50 characters in length.
        /// </summary>
        public static string hppRequest_hppSelectStoredCard_size {
            get {
                return ResourceManager.GetString("hppRequest_hppSelectStoredCard_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must only contain the numbers between 1 and 2.
        /// </summary>
        public static string hppRequest_hppVersion_pattern {
            get {
                return ResourceManager.GetString("hppRequest_hppVersion_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_hppVersion_size {
            get {
                return ResourceManager.GetString("hppRequest_hppVersion_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language must be 2 alphabetic characters only, optionally followed by an underscore and alphabetic country or region code.
        /// </summary>
        public static string hppRequest_language_pattern {
            get {
                return ResourceManager.GetString("hppRequest_language_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID must only contain alphanumeric characters.
        /// </summary>
        public static string hppRequest_merchantId_pattern {
            get {
                return ResourceManager.GetString("hppRequest_merchantId_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID is required and must be between 1 and 50 characters.
        /// </summary>
        public static string hppRequest_merchantId_size {
            get {
                return ResourceManager.GetString("hppRequest_merchantId_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer to save card flag must be 1 or 0.
        /// </summary>
        public static string hppRequest_offerSaveCard_pattern {
            get {
                return ResourceManager.GetString("hppRequest_offerSaveCard_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer to save card flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_offerSaveCard_size {
            get {
                return ResourceManager.GetString("hppRequest_offerSaveCard_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID must only contain alphanumeric characters, dash and underscore.
        /// </summary>
        public static string hppRequest_orderId_pattern {
            get {
                return ResourceManager.GetString("hppRequest_orderId_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID must be less than 50 characters in length.
        /// </summary>
        public static string hppRequest_orderId_size {
            get {
                return ResourceManager.GetString("hppRequest_orderId_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer exists flag must be 0, 1 or 2.
        /// </summary>
        public static string hppRequest_payerExists_pattern {
            get {
                return ResourceManager.GetString("hppRequest_payerExists_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer exists flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_payerExists_size {
            get {
                return ResourceManager.GetString("hppRequest_payerExists_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer reference must only contain the characters a-z A-Z\ 0-9 _ spaces.
        /// </summary>
        public static string hppRequest_payerReference_pattern {
            get {
                return ResourceManager.GetString("hppRequest_payerReference_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer reference must not be more than 50 characters in length.
        /// </summary>
        public static string hppRequest_payerReference_size {
            get {
                return ResourceManager.GetString("hppRequest_payerReference_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment reference must only contain  characters a-z A-Z 0-9 _ - spaces.
        /// </summary>
        public static string hppRequest_paymentReference_pattern {
            get {
                return ResourceManager.GetString("hppRequest_paymentReference_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment reference must not be more than 50 characters in length.
        /// </summary>
        public static string hppRequest_paymentReference_size {
            get {
                return ResourceManager.GetString("hppRequest_paymentReference_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID must only contain the characters a-z A-Z 0-9 - _ . , + @ spaces.
        /// </summary>
        public static string hppRequest_productId_pattern {
            get {
                return ResourceManager.GetString("hppRequest_productId_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID must not contain more than 50 characters.
        /// </summary>
        public static string hppRequest_productId_size {
            get {
                return ResourceManager.GetString("hppRequest_productId_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return TSS must be 1 or 0.
        /// </summary>
        public static string hppRequest_returnTss_pattern {
            get {
                return ResourceManager.GetString("hppRequest_returnTss_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return TSS flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_returnTss_size {
            get {
                return ResourceManager.GetString("hppRequest_returnTss_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping code must be of format [digits from postcode]|[digits from address] and contain only a-z A-Z 0-9 , . - / | spaces.
        /// </summary>
        public static string hppRequest_shippingCode_pattern {
            get {
                return ResourceManager.GetString("hppRequest_shippingCode_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping code must not be more than 30 characters in length.
        /// </summary>
        public static string hppRequest_shippingCode_size {
            get {
                return ResourceManager.GetString("hppRequest_shippingCode_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping country must only contain the characters A-Z a-z 0-9 , . -.
        /// </summary>
        public static string hppRequest_shippingCountry_pattern {
            get {
                return ResourceManager.GetString("hppRequest_shippingCountry_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping country must not contain more than 50 characters.
        /// </summary>
        public static string hppRequest_shippingCountry_size {
            get {
                return ResourceManager.GetString("hppRequest_shippingCountry_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp must be in YYYYMMDDHHMMSS format.
        /// </summary>
        public static string hppRequest_timestamp_pattern {
            get {
                return ResourceManager.GetString("hppRequest_timestamp_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp is required and must be 14 characters in length.
        /// </summary>
        public static string hppRequest_timestamp_size {
            get {
                return ResourceManager.GetString("hppRequest_timestamp_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate card only flag must be 1 or 0.
        /// </summary>
        public static string hppRequest_validateCardOnly_pattern {
            get {
                return ResourceManager.GetString("hppRequest_validateCardOnly_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate card only flag must not be more than 1 character in length.
        /// </summary>
        public static string hppRequest_validateCardOnly_size {
            get {
                return ResourceManager.GetString("hppRequest_validateCardOnly_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable reference must only contain the characters a-z A-Z 0-9 - _ . , + @ spaces.
        /// </summary>
        public static string hppRequest_variableReference_pattern {
            get {
                return ResourceManager.GetString("hppRequest_variableReference_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable reference must not contain more than 50 characters.
        /// </summary>
        public static string hppRequest_variableReference_size {
            get {
                return ResourceManager.GetString("hppRequest_variableReference_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined. Please check that you entered your card details correctly.
        /// </summary>
        public static string hppResponse_message_101 {
            get {
                return ResourceManager.GetString("hppResponse_message_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined. Please check that you entered your card details correctly.
        /// </summary>
        public static string hppResponse_message_102 {
            get {
                return ResourceManager.GetString("hppResponse_message_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined. Please check that you entered your card details correctly.
        /// </summary>
        public static string hppResponse_message_103 {
            get {
                return ResourceManager.GetString("hppResponse_message_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined. Please check that you entered your card details correctly.
        /// </summary>
        public static string hppResponse_message_107 {
            get {
                return ResourceManager.GetString("hppResponse_message_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined. Please check that you entered your card details correctly.
        /// </summary>
        public static string hppResponse_message_1xx {
            get {
                return ResourceManager.GetString("hppResponse_message_1xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed due to error with bank systems.
        /// </summary>
        public static string hppResponse_message_2xx {
            get {
                return ResourceManager.GetString("hppResponse_message_2xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed due to error with Realex systems.
        /// </summary>
        public static string hppResponse_message_3xx {
            get {
                return ResourceManager.GetString("hppResponse_message_3xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successful, but error processing transaction.
        /// </summary>
        public static string hppResponse_message_598 {
            get {
                return ResourceManager.GetString("hppResponse_message_598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing transaction.
        /// </summary>
        public static string hppResponse_message_599 {
            get {
                return ResourceManager.GetString("hppResponse_message_599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing transaction.
        /// </summary>
        public static string hppResponse_message_5xx {
            get {
                return ResourceManager.GetString("hppResponse_message_5xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing transaction.
        /// </summary>
        public static string hppResponse_message_666 {
            get {
                return ResourceManager.GetString("hppResponse_message_666", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing transaction.
        /// </summary>
        public static string hppResponse_message_unknown {
            get {
                return ResourceManager.GetString("hppResponse_message_unknown", resourceCulture);
            }
        }
    }
}
