//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace global.cloudis.RealexHPP
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HPPMessages
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public HPPMessages()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("global.cloudis.RealexHPP.HPPMessages", typeof(HPPMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string hppRequest_merchantId_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_merchantId_size", resourceCulture);
            }
        }

        public static string hppRequest_merchantId_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_merchantId_pattern", resourceCulture);
            }
        }

        public static string hppRequest_account_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_account_size", resourceCulture);
            }
        }

        public static string hppRequest_account_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_account_pattern", resourceCulture);
            }
        }

        public static string hppRequest_orderId_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_orderId_size", resourceCulture);
            }
        }

        public static string hppRequest_orderId_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_orderId_pattern", resourceCulture);
            }
        }

        public static string hppRequest_amount_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_amount_size", resourceCulture);
            }
        }

        public static string hppRequest_amount_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_amount_pattern", resourceCulture);
            }
        }

        public static string hppRequest_amount_otb
        {
            get
            {
                return ResourceManager.GetString("hppRequest_amount_otb", resourceCulture);
            }
        }

        public static string hppRequest_currency_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_currency_size", resourceCulture);
            }
        }

        public static string hppRequest_currency_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_currency_pattern", resourceCulture);
            }
        }

        public static string hppRequest_timestamp_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_timestamp_size", resourceCulture);
            }
        }

        public static string hppRequest_timestamp_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_timestamp_pattern", resourceCulture);
            }
        }

        public static string hppRequest_hash_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hash_size", resourceCulture);
            }
        }

        public static string hppRequest_hash_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hash_pattern", resourceCulture);
            }
        }

        public static string hppRequest_autoSettleFlag_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_autoSettleFlag_pattern", resourceCulture);
            }
        }

        public static string hppRequest_comment1_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_comment1_size", resourceCulture);
            }
        }

        public static string hppRequest_comment1_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_comment1_pattern", resourceCulture);
            }
        }

        public static string hppRequest_comment2_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_comment2_size", resourceCulture);
            }
        }

        public static string hppRequest_comment2_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_comment2_pattern", resourceCulture);
            }
        }

        public static string hppRequest_returnTss_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_returnTss_size", resourceCulture);
            }
        }

        public static string hppRequest_returnTss_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_returnTss_pattern", resourceCulture);
            }
        }

        public static string hppRequest_shippingCode_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_shippingCode_size", resourceCulture);
            }
        }

        public static string hppRequest_shippingCode_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_shippingCode_pattern", resourceCulture);
            }
        }

        public static string hppRequest_shippingCountry_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_shippingCountry_size", resourceCulture);
            }
        }

        public static string hppRequest_shippingCountry_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_shippingCountry_pattern", resourceCulture);
            }
        }

        public static string hppRequest_billingCode_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_billingCode_size", resourceCulture);
            }
        }

        public static string hppRequest_billingCode_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_billingCode_pattern", resourceCulture);
            }
        }

        public static string hppRequest_billingCountry_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_billingCountry_size", resourceCulture);
            }
        }

        public static string hppRequest_billingCountry_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_billingCountry_pattern", resourceCulture);
            }
        }

        public static string hppRequest_customerNumber_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_customerNumber_size", resourceCulture);
            }
        }

        public static string hppRequest_customerNumber_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_customerNumber_pattern", resourceCulture);
            }
        }

        public static string hppRequest_variableReference_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_variableReference_size", resourceCulture);
            }
        }

        public static string hppRequest_variableReference_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_variableReference_pattern", resourceCulture);
            }
        }

        public static string hppRequest_productId_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_productId_size", resourceCulture);
            }
        }

        public static string hppRequest_productId_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_productId_pattern", resourceCulture);
            }
        }

        public static string hppRequest_language_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_language_pattern", resourceCulture);
            }
        }

        public static string hppRequest_cardPaymentButtonText_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_cardPaymentButtonText_size", resourceCulture);
            }
        }

        public static string hppRequest_cardPaymentButtonText_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_cardPaymentButtonText_pattern", resourceCulture);
            }
        }

        public static string hppRequest_cardStorageEnable_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_cardStorageEnable_size", resourceCulture);
            }
        }

        public static string hppRequest_cardStorageEnable_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_cardStorageEnable_pattern", resourceCulture);
            }
        }

        public static string hppRequest_offerSaveCard_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_offerSaveCard_size", resourceCulture);
            }
        }

        public static string hppRequest_offerSaveCard_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_offerSaveCard_pattern", resourceCulture);
            }
        }

        public static string hppRequest_payerReference_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_payerReference_size", resourceCulture);
            }
        }

        public static string hppRequest_payerReference_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_payerReference_pattern", resourceCulture);
            }
        }

        public static string hppRequest_paymentReference_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_paymentReference_size", resourceCulture);
            }
        }

        public static string hppRequest_paymentReference_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_paymentReference_pattern", resourceCulture);
            }
        }

        public static string hppRequest_payerExists_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_payerExists_size", resourceCulture);
            }
        }

        public static string hppRequest_payerExists_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_payerExists_pattern", resourceCulture);
            }
        }

        public static string hppRequest_validateCardOnly_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_validateCardOnly_size", resourceCulture);
            }
        }

        public static string hppRequest_validateCardOnly_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_validateCardOnly_pattern", resourceCulture);
            }
        }

        public static string hppRequest_dccEnable_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_dccEnable_size", resourceCulture);
            }
        }

        public static string hppRequest_dccEnable_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_dccEnable_pattern", resourceCulture);
            }
        }

        public static string hppRequest_hppFraudFilterMode_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppFraudFilterMode_size", resourceCulture);
            }
        }

        public static string hppRequest_hppFraudFilterMode_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppFraudFilterMode_pattern", resourceCulture);
            }
        }

        public static string hppRequest_hppVersion_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppVersion_size", resourceCulture);
            }
        }

        public static string hppRequest_hppVersion_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppVersion_pattern", resourceCulture);
            }
        }

        public static string hppRequest_hppSelectStoredCard_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppSelectStoredCard_size", resourceCulture);
            }
        }

        public static string hppRequest_hppSelectStoredCard_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_hppSelectStoredCard_pattern", resourceCulture);
            }
        }

        public static string hppRequest_channel_pattern
        {
            get
            {
                return ResourceManager.GetString("hppRequest_channel_pattern", resourceCulture);
            }
        }

        public static string hppRequest_channel_size
        {
            get
            {
                return ResourceManager.GetString("hppRequest_channel_size", resourceCulture);
            }
        }

        public static string hppResponse_message_101
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_101", resourceCulture);
            }
        }

        public static string hppResponse_message_102
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_102", resourceCulture);
            }
        }

        public static string hppResponse_message_103
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_103", resourceCulture);
            }
        }

        public static string hppResponse_message_2xx
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_2xx", resourceCulture);
            }
        }

        public static string hppResponse_message_3xx
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_3xx", resourceCulture);
            }
        }

        public static string hppResponse_message_107
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_107", resourceCulture);
            }
        }

        public static string hppResponse_message_1xx
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_1xx", resourceCulture);
            }
        }

        public static string hppResponse_message_5xx
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_5xx", resourceCulture);
            }
        }

        public static string hppResponse_message_666
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_666", resourceCulture);
            }
        }

        public static string hppResponse_message_599
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_599", resourceCulture);
            }
        }

        public static string hppResponse_message_unknown
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_unknown", resourceCulture);
            }
        }

        public static string hppResponse_message_598
        {
            get
            {
                return ResourceManager.GetString("hppResponse_message_598", resourceCulture);
            }
        }
    }
}
